# Generated by Django 5.2.16 on 2026-08-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('predict-failure', 'Prédiction de panne'), ('predict-demand', 'Prévision de demande')], max_length=32)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('latence_ms', models.FloatField()),
                ('succes', models.BooleanField(default=True)),
                ('resultat_resume', models.CharField(blank=True, max_length=200)),
                ('message_erreur', models.CharField(blank=True, max_length=500)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
    ]
