# Generated by Django 5.2.16 on 2026-07-31 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('fiabilite_score', models.FloatField()),
                ('delai_moyen_livraison_jours', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PieceRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_panne_associe', models.CharField(max_length=16)),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=100)),
                ('prix_unitaire', models.FloatField()),
                ('stock_actuel', models.PositiveIntegerField()),
                ('seuil_reapprovisionnement', models.PositiveIntegerField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='inventory.fournisseur')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
