# Generated by Django 5.2.16 on 2026-07-31 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureCapteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_ai4i', models.IntegerField(unique=True)),
                ('type_produit', models.CharField(max_length=8)),
                ('temperature_air_k', models.FloatField()),
                ('temperature_process_k', models.FloatField()),
                ('vitesse_rotation_rpm', models.FloatField()),
                ('couple_nm', models.FloatField()),
                ('usure_outil_min', models.FloatField()),
                ('panne', models.BooleanField(default=False)),
                ('panne_twf', models.BooleanField(default=False)),
                ('panne_hdf', models.BooleanField(default=False)),
                ('panne_pwf', models.BooleanField(default=False)),
                ('panne_osf', models.BooleanField(default=False)),
                ('panne_rnf', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['reference_ai4i'],
            },
        ),
        migrations.CreateModel(
            name='InterventionPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_intervention', models.DateField()),
                ('cout_total', models.FloatField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='inventory.piecerechange')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='maintenance.lecturecapteur')),
            ],
            options={
                'ordering': ['-date_intervention'],
            },
        ),
    ]
